dependencies:
  flutter:
    sdk: flutter

  # In dono versions ko up to date naye versions par change kar dein
  file_picker: ^8.1.7
  shared_preferences: ^2.3.5
  flutter_plugin_android_lifecycle: ^2.0.24
