name: Build Flutter APK

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK (Without Error)
        run: |
          FLUTTER_DIR=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          cd "$FLUTTER_DIR"
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Find and Copy APK
        run: |
          mkdir -p build_output
          # Yeh line APK ko kahin se bhi dhoondh kar safe folder mein daal degi
          find . -name "app-release.apk" -exec cp {} build_output/ \;

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rent Manager APK
          path: build_output/*.apk
